const CACHE_NAME = 'automatenunsinn-v1';
const ASSETS = [
  '/',
  'index.html',
  'style.css',
  'style.js',
  'favicon.ico',
  'manifest.json',
  // Pages
  'bpatcher.html',
  'bw.html',
  'db.html',
  'game.html',
  'isp.html',
  'pt.html',
  'readout.html',
  'serial.html',
  'sm.html',
  'sound.html',
  'splitter.html',
  'teileliste.html',
  'zl.html',
  'zlk_eeprom.html',
  'zlk_v1.html',
  // Scripts & Styles (Generated by Webpack)
  'bally.js',
  'bpatcher.js',
  'bw.css',
  'bw.js',
  'db.css',
  'db.js',
  'eeprom.js',
  'fileMappings.js',
  'game.js',
  'pt.js',
  'readout.js',
  'serial.js',
  'sound.js',
  'splitter.js',
  'teileliste.js',
  'zl.js',
  'zlk_eeprom.js',
  'zlk_v1.js',
  // Data
  'teile.tsv'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      // Use cache.addAll but catch individual failures if any asset is missing
      return Promise.allSettled(
        ASSETS.map(asset => cache.add(asset))
      ).then(results => {
        const failed = results.filter(r => r.status === 'rejected');
        if (failed.length > 0) {
          console.warn('Some assets failed to cache:', failed.map(f => f.reason));
        }
      });
    })
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (cacheName !== CACHE_NAME) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
